coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 3%
    patch:
      default:
        target: 80%
        threshold: 3%

comment:
  layout: "condensed_header, diff, flags, components"
  require_changes: true